# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: devHome
      directives:
        description: Installing Microsoft.DevHome
        allowPrerelease: true
      settings:
        id: Microsoft.DevHome
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powershell
      directives:
        description: Install PowerShell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: windowsTerminal
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohMyPosh
      directives:
        description: Install oh-my-posh
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: visualstudiocommunity
      directives:
        description: Install Visual Studio Community
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Community.Preview
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azureDataStudio
      directives:
        description: Install Azure Data Studio
        allowPrerelease: true
      settings:
        id: Microsoft.AzureDataStudio
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azureCli
      directives:
        description: Install Azure CLI
        allowPrerelease: true
      settings:
        id: Microsoft.AzureCLI
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azureDeveloperCli
      directives:
        description: Install Azure Developer CLI
        allowPrerelease: true
      settings:
        id: Microsoft.Azd
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: bicep
      directives:
        description: Install Bicep
        allowPrerelease: true
      settings:
        id: Microsoft.Bicep
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: storageExplorer
      directives:
        description: Install Microsoft Storage Explorer
        allowPrerelease: true
      settings:
        id: Microsoft.Azure.StorageExplorer
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: cosmosEmulator
      directives:
        description: Install Azure Cosmos Emulator
        allowPrerelease: true
      settings:
        id: Microsoft.Azure.CosmosEmulator
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azureFunctionsCoreTools
      directives:
        description: Install Azure Functions Core Tools
        allowPrerelease: true
      settings:
        id: Microsoft.Azure.FunctionsCoreTools
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dotnet8sdk
      directives:
        description: Install .NET 8 SDK
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.SDK.8
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nodejs
      directives:
        description: Install Node.js
        allowPrerelease: true
      settings:
        id: OpenJS.NodeJS
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nvm
      directives:
        description: Install NVM for Windows
        allowPrerelease: true
      settings:
        id: CoreyButler.NVMforWindows
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: bun
      directives:
        description: Install Bun
        allowPrerelease: true
      settings:
        id: Oven-sh.Bun
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: devtoys
      directives:
        description: Install DevToys
        allowPrerelease: true
      settings:
        id: 9PGCV4V3BK4W
        source: msstore
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: bruno
      directives:
        description: Install Bruno
        allowPrerelease: true
      settings:
        id: Bruno.Bruno
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: k9s
      directives:
        description: Install k9s
        allowPrerelease: true
      settings:
        id: Derailed.k9s
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dockerDesktop
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        id: Docker.DockerDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gitKraken
      directives:
        description: Install GitKraken
        allowPrerelease: true
      settings:
        id: Axosoft.GitKraken
        source: winget
  configurationVersion: 0.2.0
